name = "paper"
license = "MIT"
licenselink = "https://github.com/tanaka0325/paper/blob/master/LICENSE"
description = "simple hugo theme"
homepage = "https://github.com/tanaka0325/paper"
tags = ["blog", "minimal", "responsive"]
features = ["blog", "themes", "minimal", "responsive"]
min_version = "0.41"

[author]
  name = "Hiroyuki Tanaka"
  homepage = "https://tanaka0325.github.io"
